name: BRVM Daily Update

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  run-brvm-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer les packages R
        run: |
          Rscript -e 'install.packages(c("BRVM", "openxlsx"))'

      - name: Lancer le script
        run: Rscript brvm_auto_update.R

      - name: Enregistrer le fichier Excel
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add BRVM_Cours_Quotidiens.xlsx
          git commit -m "🕒 Mise à jour automatique BRVM - $(date +'%F')"
          git push
